2024-08-09 04:26:48,784 - distributed.nanny - INFO -         Start Nanny at: 'tcp://10.34.59.10:46409'
2024-08-09 04:26:48,788 - distributed.nanny - INFO -         Start Nanny at: 'tcp://10.34.59.10:34414'
2024-08-09 04:26:49,383 - distributed.diskutils - INFO - Found stale lock file and directory '/tmp/dask-scratch-space/worker-8aw5e262', purging
2024-08-09 04:26:49,384 - distributed.diskutils - INFO - Found stale lock file and directory '/tmp/dask-scratch-space/worker-uitxj5sx', purging
2024-08-09 04:26:49,894 - distributed.worker - INFO -       Start worker at:    tcp://10.34.59.10:34734
2024-08-09 04:26:49,894 - distributed.worker - INFO -       Start worker at:    tcp://10.34.59.10:35477
2024-08-09 04:26:49,894 - distributed.worker - INFO -          Listening to:    tcp://10.34.59.10:34734
2024-08-09 04:26:49,894 - distributed.worker - INFO -          Listening to:    tcp://10.34.59.10:35477
2024-08-09 04:26:49,894 - distributed.worker - INFO -           Worker name:           SLURMCluster-0-1
2024-08-09 04:26:49,894 - distributed.worker - INFO -           Worker name:           SLURMCluster-0-0
2024-08-09 04:26:49,894 - distributed.worker - INFO -          dashboard at:          10.34.59.10:43589
2024-08-09 04:26:49,894 - distributed.worker - INFO -          dashboard at:          10.34.59.10:35898
2024-08-09 04:26:49,894 - distributed.worker - INFO - Waiting to connect to:     tcp://10.34.59.1:38478
2024-08-09 04:26:49,894 - distributed.worker - INFO - Waiting to connect to:     tcp://10.34.59.1:38478
2024-08-09 04:26:49,894 - distributed.worker - INFO - -------------------------------------------------
2024-08-09 04:26:49,894 - distributed.worker - INFO - -------------------------------------------------
2024-08-09 04:26:49,894 - distributed.worker - INFO -               Threads:                          1
2024-08-09 04:26:49,894 - distributed.worker - INFO -               Threads:                          1
2024-08-09 04:26:49,894 - distributed.worker - INFO -                Memory:                   1.86 GiB
2024-08-09 04:26:49,894 - distributed.worker - INFO -                Memory:                   1.86 GiB
2024-08-09 04:26:49,894 - distributed.worker - INFO -       Local Directory: /tmp/dask-scratch-space/worker-grstvzcw
2024-08-09 04:26:49,894 - distributed.worker - INFO -       Local Directory: /tmp/dask-scratch-space/worker-qir3q5yz
2024-08-09 04:26:49,894 - distributed.worker - INFO - -------------------------------------------------
2024-08-09 04:26:49,895 - distributed.worker - INFO - -------------------------------------------------
2024-08-09 04:26:50,293 - distributed.worker - INFO - Starting Worker plugin shuffle
2024-08-09 04:26:50,293 - distributed.worker - INFO -         Registered to:     tcp://10.34.59.1:38478
2024-08-09 04:26:50,293 - distributed.worker - INFO - -------------------------------------------------
2024-08-09 04:26:50,293 - distributed.worker - INFO - Starting Worker plugin shuffle
2024-08-09 04:26:50,293 - distributed.core - INFO - Starting established connection to tcp://10.34.59.1:38478
2024-08-09 04:26:50,294 - distributed.worker - INFO -         Registered to:     tcp://10.34.59.1:38478
2024-08-09 04:26:50,294 - distributed.worker - INFO - -------------------------------------------------
2024-08-09 04:26:50,294 - distributed.core - INFO - Starting established connection to tcp://10.34.59.1:38478
slurmstepd: error: *** JOB 2329055 ON cl-node010 CANCELLED AT 2024-08-09T04:26:58 ***
2024-08-09 04:26:58,443 - distributed.worker - INFO - Stopping worker at tcp://10.34.59.10:35477. Reason: scheduler-close
2024-08-09 04:26:58,443 - distributed.worker - INFO - Stopping worker at tcp://10.34.59.10:34734. Reason: scheduler-close
2024-08-09 04:26:58,444 - distributed.batched - INFO - Batched Comm Closed <TCP (closed) Worker->Scheduler local=tcp://10.34.59.10:53134 remote=tcp://10.34.59.1:38478>
Traceback (most recent call last):
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/distributed/comm/tcp.py", line 297, in write
    raise StreamClosedError()
tornado.iostream.StreamClosedError: Stream is closed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/distributed/batched.py", line 115, in _background_send
    nbytes = yield coro
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/tornado/gen.py", line 767, in run
    value = future.result()
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/distributed/comm/tcp.py", line 307, in write
    convert_stream_closed_error(self, e)
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/distributed/comm/tcp.py", line 142, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed) Worker->Scheduler local=tcp://10.34.59.10:53134 remote=tcp://10.34.59.1:38478>: Stream is closed
2024-08-09 04:26:58,447 - distributed.nanny - INFO - Closing Nanny gracefully at 'tcp://10.34.59.10:46409'. Reason: scheduler-close
2024-08-09 04:26:58,446 - distributed.batched - INFO - Batched Comm Closed <TCP (closed) Worker->Scheduler local=tcp://10.34.59.10:53136 remote=tcp://10.34.59.1:38478>
Traceback (most recent call last):
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/distributed/comm/tcp.py", line 297, in write
    raise StreamClosedError()
tornado.iostream.StreamClosedError: Stream is closed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/distributed/batched.py", line 115, in _background_send
    nbytes = yield coro
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/tornado/gen.py", line 767, in run
    value = future.result()
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/distributed/comm/tcp.py", line 307, in write
    convert_stream_closed_error(self, e)
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/distributed/comm/tcp.py", line 142, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed) Worker->Scheduler local=tcp://10.34.59.10:53136 remote=tcp://10.34.59.1:38478>: Stream is closed
2024-08-09 04:26:58,449 - distributed.core - INFO - Received 'close-stream' from tcp://10.34.59.1:38478; closing.
2024-08-09 04:26:58,449 - distributed.nanny - INFO - Closing Nanny gracefully at 'tcp://10.34.59.10:34414'. Reason: scheduler-close
2024-08-09 04:26:58,449 - distributed.nanny - INFO - Worker closed
2024-08-09 04:26:58,452 - distributed.core - INFO - Received 'close-stream' from tcp://10.34.59.1:38478; closing.
2024-08-09 04:26:58,452 - distributed.nanny - INFO - Worker closed
