2024-08-09 04:24:40,731 - distributed.nanny - INFO -         Start Nanny at: 'tcp://10.34.59.8:32874'
2024-08-09 04:24:41,326 - distributed.diskutils - INFO - Found stale lock file and directory '/tmp/dask-scratch-space/worker-feq8coc6', purging
2024-08-09 04:24:41,850 - distributed.worker - INFO -       Start worker at:     tcp://10.34.59.8:43154
2024-08-09 04:24:41,850 - distributed.worker - INFO -          Listening to:     tcp://10.34.59.8:43154
2024-08-09 04:24:41,850 - distributed.worker - INFO -           Worker name:             SLURMCluster-7
2024-08-09 04:24:41,850 - distributed.worker - INFO -          dashboard at:           10.34.59.8:43611
2024-08-09 04:24:41,850 - distributed.worker - INFO - Waiting to connect to:     tcp://10.34.59.1:43007
2024-08-09 04:24:41,850 - distributed.worker - INFO - -------------------------------------------------
2024-08-09 04:24:41,850 - distributed.worker - INFO -               Threads:                          1
2024-08-09 04:24:41,850 - distributed.worker - INFO -                Memory:                   1.86 GiB
2024-08-09 04:24:41,850 - distributed.worker - INFO -       Local Directory: /tmp/dask-scratch-space/worker-rqll1oto
2024-08-09 04:24:41,850 - distributed.worker - INFO - -------------------------------------------------
2024-08-09 04:24:42,208 - distributed.worker - INFO - Starting Worker plugin shuffle
2024-08-09 04:24:42,209 - distributed.worker - INFO -         Registered to:     tcp://10.34.59.1:43007
2024-08-09 04:24:42,209 - distributed.worker - INFO - -------------------------------------------------
2024-08-09 04:24:42,209 - distributed.core - INFO - Starting established connection to tcp://10.34.59.1:43007
slurmstepd: error: *** JOB 2329005 ON cl-node008 CANCELLED AT 2024-08-09T04:24:51 ***
2024-08-09 04:24:51,115 - distributed.worker - INFO - Stopping worker at tcp://10.34.59.8:43154. Reason: scheduler-close
2024-08-09 04:24:51,117 - distributed.batched - INFO - Batched Comm Closed <TCP (closed) Worker->Scheduler local=tcp://10.34.59.8:60922 remote=tcp://10.34.59.1:43007>
Traceback (most recent call last):
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/distributed/comm/tcp.py", line 297, in write
    raise StreamClosedError()
tornado.iostream.StreamClosedError: Stream is closed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/distributed/batched.py", line 115, in _background_send
    nbytes = yield coro
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/tornado/gen.py", line 767, in run
    value = future.result()
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/distributed/comm/tcp.py", line 307, in write
    convert_stream_closed_error(self, e)
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/distributed/comm/tcp.py", line 142, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed) Worker->Scheduler local=tcp://10.34.59.8:60922 remote=tcp://10.34.59.1:43007>: Stream is closed
