2024-08-09 04:25:23,689 - distributed.nanny - INFO -         Start Nanny at: 'tcp://10.34.59.10:37788'
2024-08-09 04:25:24,287 - distributed.diskutils - INFO - Found stale lock file and directory '/tmp/dask-scratch-space/worker-q38sfuaa', purging
2024-08-09 04:25:24,769 - distributed.worker - INFO -       Start worker at:    tcp://10.34.59.10:46415
2024-08-09 04:25:24,769 - distributed.worker - INFO -          Listening to:    tcp://10.34.59.10:46415
2024-08-09 04:25:24,769 - distributed.worker - INFO -           Worker name:             SLURMCluster-2
2024-08-09 04:25:24,769 - distributed.worker - INFO -          dashboard at:          10.34.59.10:43825
2024-08-09 04:25:24,769 - distributed.worker - INFO - Waiting to connect to:     tcp://10.34.59.1:43877
2024-08-09 04:25:24,769 - distributed.worker - INFO - -------------------------------------------------
2024-08-09 04:25:24,769 - distributed.worker - INFO -               Threads:                          1
2024-08-09 04:25:24,769 - distributed.worker - INFO -                Memory:                   1.86 GiB
2024-08-09 04:25:24,769 - distributed.worker - INFO -       Local Directory: /tmp/dask-scratch-space/worker-b467mu9b
2024-08-09 04:25:24,770 - distributed.worker - INFO - -------------------------------------------------
2024-08-09 04:25:25,136 - distributed.worker - INFO - Starting Worker plugin shuffle
2024-08-09 04:25:25,136 - distributed.worker - INFO -         Registered to:     tcp://10.34.59.1:43877
2024-08-09 04:25:25,136 - distributed.worker - INFO - -------------------------------------------------
2024-08-09 04:25:25,137 - distributed.core - INFO - Starting established connection to tcp://10.34.59.1:43877
slurmstepd: error: *** JOB 2329023 ON cl-node010 CANCELLED AT 2024-08-09T04:25:34 ***
2024-08-09 04:25:34,097 - distributed.worker - INFO - Stopping worker at tcp://10.34.59.10:46415. Reason: scheduler-close
2024-08-09 04:25:34,099 - distributed.batched - INFO - Batched Comm Closed <TCP (closed) Worker->Scheduler local=tcp://10.34.59.10:58778 remote=tcp://10.34.59.1:43877>
Traceback (most recent call last):
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/distributed/comm/tcp.py", line 297, in write
    raise StreamClosedError()
tornado.iostream.StreamClosedError: Stream is closed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/distributed/batched.py", line 115, in _background_send
    nbytes = yield coro
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/tornado/gen.py", line 767, in run
    value = future.result()
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/distributed/comm/tcp.py", line 307, in write
    convert_stream_closed_error(self, e)
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/distributed/comm/tcp.py", line 142, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed) Worker->Scheduler local=tcp://10.34.59.10:58778 remote=tcp://10.34.59.1:43877>: Stream is closed
2024-08-09 04:25:34,103 - distributed.nanny - INFO - Closing Nanny gracefully at 'tcp://10.34.59.10:37788'. Reason: scheduler-close
2024-08-09 04:25:34,106 - distributed.core - INFO - Received 'close-stream' from tcp://10.34.59.1:43877; closing.
2024-08-09 04:25:34,106 - distributed.nanny - INFO - Worker closed
