2024-08-09 07:56:45,236 - distributed.nanny - INFO -         Start Nanny at: 'tcp://10.34.59.6:46174'
2024-08-09 07:56:45,832 - distributed.diskutils - INFO - Found stale lock file and directory '/tmp/dask-scratch-space/worker-w11d5qg_', purging
2024-08-09 07:56:46,355 - distributed.worker - INFO -       Start worker at:     tcp://10.34.59.6:43033
2024-08-09 07:56:46,355 - distributed.worker - INFO -          Listening to:     tcp://10.34.59.6:43033
2024-08-09 07:56:46,355 - distributed.worker - INFO -           Worker name:             SLURMCluster-1
2024-08-09 07:56:46,355 - distributed.worker - INFO -          dashboard at:           10.34.59.6:40520
2024-08-09 07:56:46,355 - distributed.worker - INFO - Waiting to connect to:     tcp://10.34.59.1:40851
2024-08-09 07:56:46,355 - distributed.worker - INFO - -------------------------------------------------
2024-08-09 07:56:46,355 - distributed.worker - INFO -               Threads:                          1
2024-08-09 07:56:46,355 - distributed.worker - INFO -                Memory:                   1.86 GiB
2024-08-09 07:56:46,355 - distributed.worker - INFO -       Local Directory: /tmp/dask-scratch-space/worker-4yoa7cqd
2024-08-09 07:56:46,355 - distributed.worker - INFO - -------------------------------------------------
2024-08-09 07:56:46,772 - distributed.worker - INFO - Starting Worker plugin shuffle
2024-08-09 07:56:46,772 - distributed.worker - INFO -         Registered to:     tcp://10.34.59.1:40851
2024-08-09 07:56:46,772 - distributed.worker - INFO - -------------------------------------------------
2024-08-09 07:56:46,773 - distributed.core - INFO - Starting established connection to tcp://10.34.59.1:40851
2024-08-09 07:57:47,574 - distributed.worker - INFO - Stopping worker at tcp://10.34.59.6:43033. Reason: scheduler-close
slurmstepd: error: *** JOB 2331228 ON cl-node006 CANCELLED AT 2024-08-09T07:57:47 ***
2024-08-09 07:57:47,576 - distributed.batched - INFO - Batched Comm Closed <TCP (closed) Worker->Scheduler local=tcp://10.34.59.6:52484 remote=tcp://10.34.59.1:40851>
Traceback (most recent call last):
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/distributed/comm/tcp.py", line 297, in write
    raise StreamClosedError()
tornado.iostream.StreamClosedError: Stream is closed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/distributed/batched.py", line 115, in _background_send
    nbytes = yield coro
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/tornado/gen.py", line 767, in run
    value = future.result()
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/distributed/comm/tcp.py", line 307, in write
    convert_stream_closed_error(self, e)
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/distributed/comm/tcp.py", line 142, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed) Worker->Scheduler local=tcp://10.34.59.6:52484 remote=tcp://10.34.59.1:40851>: Stream is closed
2024-08-09 07:57:47,581 - distributed.nanny - INFO - Closing Nanny gracefully at 'tcp://10.34.59.6:46174'. Reason: scheduler-close
2024-08-09 07:57:47,584 - distributed.core - INFO - Received 'close-stream' from tcp://10.34.59.1:40851; closing.
2024-08-09 07:57:47,584 - distributed.nanny - INFO - Worker closed
