2024-08-09 06:39:01,651 - distributed.nanny - INFO -         Start Nanny at: 'tcp://10.34.59.17:37077'
2024-08-09 06:39:02,243 - distributed.diskutils - INFO - Found stale lock file and directory '/tmp/dask-scratch-space/worker-tt0004r8', purging
2024-08-09 06:39:02,714 - distributed.worker - INFO -       Start worker at:    tcp://10.34.59.17:41371
2024-08-09 06:39:02,714 - distributed.worker - INFO -          Listening to:    tcp://10.34.59.17:41371
2024-08-09 06:39:02,714 - distributed.worker - INFO -           Worker name:            SLURMCluster-13
2024-08-09 06:39:02,714 - distributed.worker - INFO -          dashboard at:          10.34.59.17:44388
2024-08-09 06:39:02,714 - distributed.worker - INFO - Waiting to connect to:     tcp://10.34.59.1:33337
2024-08-09 06:39:02,714 - distributed.worker - INFO - -------------------------------------------------
2024-08-09 06:39:02,714 - distributed.worker - INFO -               Threads:                          1
2024-08-09 06:39:02,714 - distributed.worker - INFO -                Memory:                   1.86 GiB
2024-08-09 06:39:02,714 - distributed.worker - INFO -       Local Directory: /tmp/dask-scratch-space/worker-mx4gnv6_
2024-08-09 06:39:02,714 - distributed.worker - INFO - -------------------------------------------------
2024-08-09 06:39:03,070 - distributed.worker - INFO - Starting Worker plugin shuffle
2024-08-09 06:39:03,070 - distributed.worker - INFO -         Registered to:     tcp://10.34.59.1:33337
2024-08-09 06:39:03,071 - distributed.worker - INFO - -------------------------------------------------
2024-08-09 06:39:03,071 - distributed.core - INFO - Starting established connection to tcp://10.34.59.1:33337
slurmstepd: error: *** JOB 2330764 ON cl-node017 CANCELLED AT 2024-08-09T06:39:14 ***
2024-08-09 06:39:14,684 - distributed.worker - INFO - Stopping worker at tcp://10.34.59.17:41371. Reason: scheduler-close
2024-08-09 06:39:14,685 - distributed.batched - INFO - Batched Comm Closed <TCP (closed) Worker->Scheduler local=tcp://10.34.59.17:58596 remote=tcp://10.34.59.1:33337>
Traceback (most recent call last):
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/distributed/comm/tcp.py", line 297, in write
    raise StreamClosedError()
tornado.iostream.StreamClosedError: Stream is closed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/distributed/batched.py", line 115, in _background_send
    nbytes = yield coro
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/tornado/gen.py", line 767, in run
    value = future.result()
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/distributed/comm/tcp.py", line 307, in write
    convert_stream_closed_error(self, e)
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/distributed/comm/tcp.py", line 142, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed) Worker->Scheduler local=tcp://10.34.59.17:58596 remote=tcp://10.34.59.1:33337>: Stream is closed
2024-08-09 06:39:14,689 - distributed.nanny - INFO - Closing Nanny gracefully at 'tcp://10.34.59.17:37077'. Reason: scheduler-close
2024-08-09 06:39:14,691 - distributed.core - INFO - Received 'close-stream' from tcp://10.34.59.1:33337; closing.
2024-08-09 06:39:14,691 - distributed.nanny - INFO - Worker closed
