2024-08-09 06:16:28,660 - distributed.nanny - INFO -         Start Nanny at: 'tcp://10.34.59.6:37796'
2024-08-09 06:16:29,727 - distributed.worker - INFO -       Start worker at:     tcp://10.34.59.6:44743
2024-08-09 06:16:29,727 - distributed.worker - INFO -          Listening to:     tcp://10.34.59.6:44743
2024-08-09 06:16:29,727 - distributed.worker - INFO -           Worker name:             SLURMCluster-2
2024-08-09 06:16:29,727 - distributed.worker - INFO -          dashboard at:           10.34.59.6:33040
2024-08-09 06:16:29,727 - distributed.worker - INFO - Waiting to connect to:     tcp://10.34.59.1:44360
2024-08-09 06:16:29,727 - distributed.worker - INFO - -------------------------------------------------
2024-08-09 06:16:29,727 - distributed.worker - INFO -               Threads:                          1
2024-08-09 06:16:29,727 - distributed.worker - INFO -                Memory:                   1.86 GiB
2024-08-09 06:16:29,727 - distributed.worker - INFO -       Local Directory: /tmp/dask-scratch-space/worker-_rm8kpkj
2024-08-09 06:16:29,727 - distributed.worker - INFO - -------------------------------------------------
2024-08-09 06:16:30,082 - distributed.worker - INFO - Starting Worker plugin shuffle
2024-08-09 06:16:30,083 - distributed.worker - INFO -         Registered to:     tcp://10.34.59.1:44360
2024-08-09 06:16:30,083 - distributed.worker - INFO - -------------------------------------------------
2024-08-09 06:16:30,083 - distributed.core - INFO - Starting established connection to tcp://10.34.59.1:44360
2024-08-09 06:17:06,966 - distributed.worker - INFO - Stopping worker at tcp://10.34.59.6:44743. Reason: scheduler-close
2024-08-09 06:17:06,967 - distributed.batched - INFO - Batched Comm Closed <TCP (closed) Worker->Scheduler local=tcp://10.34.59.6:46312 remote=tcp://10.34.59.1:44360>
Traceback (most recent call last):
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/distributed/comm/tcp.py", line 297, in write
    raise StreamClosedError()
tornado.iostream.StreamClosedError: Stream is closed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/distributed/batched.py", line 115, in _background_send
    nbytes = yield coro
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/tornado/gen.py", line 767, in run
    value = future.result()
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/distributed/comm/tcp.py", line 307, in write
    convert_stream_closed_error(self, e)
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/distributed/comm/tcp.py", line 142, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed) Worker->Scheduler local=tcp://10.34.59.6:46312 remote=tcp://10.34.59.1:44360>: Stream is closed
2024-08-09 06:17:06,971 - distributed.nanny - INFO - Closing Nanny gracefully at 'tcp://10.34.59.6:37796'. Reason: scheduler-close
slurmstepd: error: *** JOB 2330441 ON cl-node006 CANCELLED AT 2024-08-09T06:17:06 ***
2024-08-09 06:17:06,974 - distributed.core - INFO - Received 'close-stream' from tcp://10.34.59.1:44360; closing.
2024-08-09 06:17:06,974 - distributed.nanny - INFO - Worker closed
