2024-08-09 06:30:27,267 - distributed.nanny - INFO -         Start Nanny at: 'tcp://10.34.59.10:45094'
2024-08-09 06:30:27,861 - distributed.diskutils - INFO - Found stale lock file and directory '/tmp/dask-scratch-space/worker-63ge8js4', purging
2024-08-09 06:30:28,387 - distributed.worker - INFO -       Start worker at:    tcp://10.34.59.10:34216
2024-08-09 06:30:28,387 - distributed.worker - INFO -          Listening to:    tcp://10.34.59.10:34216
2024-08-09 06:30:28,387 - distributed.worker - INFO -           Worker name:             SLURMCluster-3
2024-08-09 06:30:28,387 - distributed.worker - INFO -          dashboard at:          10.34.59.10:41135
2024-08-09 06:30:28,387 - distributed.worker - INFO - Waiting to connect to:     tcp://10.34.59.1:36146
2024-08-09 06:30:28,387 - distributed.worker - INFO - -------------------------------------------------
2024-08-09 06:30:28,387 - distributed.worker - INFO -               Threads:                          1
2024-08-09 06:30:28,387 - distributed.worker - INFO -                Memory:                   1.86 GiB
2024-08-09 06:30:28,387 - distributed.worker - INFO -       Local Directory: /tmp/dask-scratch-space/worker-hpxnnsr4
2024-08-09 06:30:28,387 - distributed.worker - INFO - -------------------------------------------------
2024-08-09 06:30:28,792 - distributed.worker - INFO - Starting Worker plugin shuffle
2024-08-09 06:30:28,792 - distributed.worker - INFO -         Registered to:     tcp://10.34.59.1:36146
2024-08-09 06:30:28,793 - distributed.worker - INFO - -------------------------------------------------
2024-08-09 06:30:28,793 - distributed.core - INFO - Starting established connection to tcp://10.34.59.1:36146
slurmstepd: error: *** JOB 2330573 ON cl-node010 CANCELLED AT 2024-08-09T06:30:47 ***
2024-08-09 06:30:47,520 - distributed.worker - INFO - Stopping worker at tcp://10.34.59.10:34216. Reason: scheduler-close
2024-08-09 06:30:47,521 - distributed.batched - INFO - Batched Comm Closed <TCP (closed) Worker->Scheduler local=tcp://10.34.59.10:49390 remote=tcp://10.34.59.1:36146>
Traceback (most recent call last):
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/distributed/comm/tcp.py", line 297, in write
    raise StreamClosedError()
tornado.iostream.StreamClosedError: Stream is closed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/distributed/batched.py", line 115, in _background_send
    nbytes = yield coro
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/tornado/gen.py", line 767, in run
    value = future.result()
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/distributed/comm/tcp.py", line 307, in write
    convert_stream_closed_error(self, e)
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/distributed/comm/tcp.py", line 142, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed) Worker->Scheduler local=tcp://10.34.59.10:49390 remote=tcp://10.34.59.1:36146>: Stream is closed
2024-08-09 06:30:47,523 - distributed.nanny - INFO - Closing Nanny gracefully at 'tcp://10.34.59.10:45094'. Reason: scheduler-close
2024-08-09 06:30:47,526 - distributed.core - INFO - Received 'close-stream' from tcp://10.34.59.1:36146; closing.
2024-08-09 06:30:47,526 - distributed.nanny - INFO - Worker closed
