2024-08-09 06:18:07,676 - distributed.nanny - INFO -         Start Nanny at: 'tcp://10.34.59.6:33275'
2024-08-09 06:18:08,746 - distributed.worker - INFO -       Start worker at:     tcp://10.34.59.6:44397
2024-08-09 06:18:08,746 - distributed.worker - INFO -          Listening to:     tcp://10.34.59.6:44397
2024-08-09 06:18:08,746 - distributed.worker - INFO -           Worker name:             SLURMCluster-1
2024-08-09 06:18:08,746 - distributed.worker - INFO -          dashboard at:           10.34.59.6:36516
2024-08-09 06:18:08,746 - distributed.worker - INFO - Waiting to connect to:     tcp://10.34.59.1:38927
2024-08-09 06:18:08,746 - distributed.worker - INFO - -------------------------------------------------
2024-08-09 06:18:08,746 - distributed.worker - INFO -               Threads:                          1
2024-08-09 06:18:08,746 - distributed.worker - INFO -                Memory:                   1.86 GiB
2024-08-09 06:18:08,746 - distributed.worker - INFO -       Local Directory: /tmp/dask-scratch-space/worker-q0md4y7t
2024-08-09 06:18:08,746 - distributed.worker - INFO - -------------------------------------------------
2024-08-09 06:18:09,098 - distributed.worker - INFO - Starting Worker plugin shuffle
2024-08-09 06:18:09,099 - distributed.worker - INFO -         Registered to:     tcp://10.34.59.1:38927
2024-08-09 06:18:09,099 - distributed.worker - INFO - -------------------------------------------------
2024-08-09 06:18:09,099 - distributed.core - INFO - Starting established connection to tcp://10.34.59.1:38927
2024-08-09 06:18:45,083 - distributed.worker - INFO - Stopping worker at tcp://10.34.59.6:44397. Reason: scheduler-close
2024-08-09 06:18:45,084 - distributed.batched - INFO - Batched Comm Closed <TCP (closed) Worker->Scheduler local=tcp://10.34.59.6:59848 remote=tcp://10.34.59.1:38927>
Traceback (most recent call last):
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/distributed/comm/tcp.py", line 297, in write
    raise StreamClosedError()
tornado.iostream.StreamClosedError: Stream is closed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/distributed/batched.py", line 115, in _background_send
    nbytes = yield coro
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/tornado/gen.py", line 767, in run
    value = future.result()
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/distributed/comm/tcp.py", line 307, in write
    convert_stream_closed_error(self, e)
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/distributed/comm/tcp.py", line 142, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed) Worker->Scheduler local=tcp://10.34.59.6:59848 remote=tcp://10.34.59.1:38927>: Stream is closed
2024-08-09 06:18:45,087 - distributed.nanny - INFO - Closing Nanny gracefully at 'tcp://10.34.59.6:33275'. Reason: scheduler-close
slurmstepd: error: *** JOB 2330449 ON cl-node006 CANCELLED AT 2024-08-09T06:18:45 ***
2024-08-09 06:18:45,089 - distributed.core - INFO - Received 'close-stream' from tcp://10.34.59.1:38927; closing.
2024-08-09 06:18:45,089 - distributed.nanny - INFO - Worker closed
