2024-08-09 06:20:18,226 - distributed.nanny - INFO -         Start Nanny at: 'tcp://10.34.59.5:43517'
2024-08-09 06:20:18,231 - distributed.nanny - INFO -         Start Nanny at: 'tcp://10.34.59.5:35957'
2024-08-09 06:20:18,827 - distributed.diskutils - INFO - Found stale lock file and directory '/tmp/dask-scratch-space/worker-wp3uxtms', purging
2024-08-09 06:20:18,828 - distributed.diskutils - INFO - Found stale lock file and directory '/tmp/dask-scratch-space/worker-_edgeljy', purging
2024-08-09 06:20:19,345 - distributed.worker - INFO -       Start worker at:     tcp://10.34.59.5:40265
2024-08-09 06:20:19,345 - distributed.worker - INFO -          Listening to:     tcp://10.34.59.5:40265
2024-08-09 06:20:19,345 - distributed.worker - INFO -           Worker name:           SLURMCluster-2-1
2024-08-09 06:20:19,345 - distributed.worker - INFO -       Start worker at:     tcp://10.34.59.5:34171
2024-08-09 06:20:19,345 - distributed.worker - INFO -          dashboard at:           10.34.59.5:35123
2024-08-09 06:20:19,346 - distributed.worker - INFO -          Listening to:     tcp://10.34.59.5:34171
2024-08-09 06:20:19,346 - distributed.worker - INFO - Waiting to connect to:     tcp://10.34.59.1:41731
2024-08-09 06:20:19,346 - distributed.worker - INFO - -------------------------------------------------
2024-08-09 06:20:19,346 - distributed.worker - INFO -           Worker name:           SLURMCluster-2-0
2024-08-09 06:20:19,346 - distributed.worker - INFO -               Threads:                          1
2024-08-09 06:20:19,346 - distributed.worker - INFO -          dashboard at:           10.34.59.5:40535
2024-08-09 06:20:19,346 - distributed.worker - INFO -                Memory:                   1.86 GiB
2024-08-09 06:20:19,346 - distributed.worker - INFO - Waiting to connect to:     tcp://10.34.59.1:41731
2024-08-09 06:20:19,346 - distributed.worker - INFO -       Local Directory: /tmp/dask-scratch-space/worker-wy1_4u3c
2024-08-09 06:20:19,346 - distributed.worker - INFO - -------------------------------------------------
2024-08-09 06:20:19,346 - distributed.worker - INFO -               Threads:                          1
2024-08-09 06:20:19,346 - distributed.worker - INFO - -------------------------------------------------
2024-08-09 06:20:19,346 - distributed.worker - INFO -                Memory:                   1.86 GiB
2024-08-09 06:20:19,346 - distributed.worker - INFO -       Local Directory: /tmp/dask-scratch-space/worker-kr4_p9py
2024-08-09 06:20:19,346 - distributed.worker - INFO - -------------------------------------------------
2024-08-09 06:20:19,745 - distributed.worker - INFO - Starting Worker plugin shuffle
2024-08-09 06:20:19,745 - distributed.worker - INFO -         Registered to:     tcp://10.34.59.1:41731
2024-08-09 06:20:19,745 - distributed.worker - INFO - -------------------------------------------------
2024-08-09 06:20:19,746 - distributed.core - INFO - Starting established connection to tcp://10.34.59.1:41731
2024-08-09 06:20:19,746 - distributed.worker - INFO - Starting Worker plugin shuffle
2024-08-09 06:20:19,746 - distributed.worker - INFO -         Registered to:     tcp://10.34.59.1:41731
2024-08-09 06:20:19,746 - distributed.worker - INFO - -------------------------------------------------
2024-08-09 06:20:19,747 - distributed.core - INFO - Starting established connection to tcp://10.34.59.1:41731
slurmstepd: error: *** JOB 2330460 ON cl-node005 CANCELLED AT 2024-08-09T06:20:37 ***
2024-08-09 06:20:37,815 - distributed.worker - INFO - Stopping worker at tcp://10.34.59.5:34171. Reason: scheduler-close
2024-08-09 06:20:37,815 - distributed.worker - INFO - Stopping worker at tcp://10.34.59.5:40265. Reason: scheduler-close
2024-08-09 06:20:37,816 - distributed.batched - INFO - Batched Comm Closed <TCP (closed) Worker->Scheduler local=tcp://10.34.59.5:49166 remote=tcp://10.34.59.1:41731>
Traceback (most recent call last):
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/distributed/comm/tcp.py", line 297, in write
    raise StreamClosedError()
tornado.iostream.StreamClosedError: Stream is closed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/distributed/batched.py", line 115, in _background_send
    nbytes = yield coro
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/tornado/gen.py", line 767, in run
    value = future.result()
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/distributed/comm/tcp.py", line 307, in write
    convert_stream_closed_error(self, e)
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/distributed/comm/tcp.py", line 142, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed) Worker->Scheduler local=tcp://10.34.59.5:49166 remote=tcp://10.34.59.1:41731>: Stream is closed
2024-08-09 06:20:37,818 - distributed.nanny - INFO - Closing Nanny gracefully at 'tcp://10.34.59.5:43517'. Reason: scheduler-close
2024-08-09 06:20:37,817 - distributed.batched - INFO - Batched Comm Closed <TCP (closed) Worker->Scheduler local=tcp://10.34.59.5:49164 remote=tcp://10.34.59.1:41731>
Traceback (most recent call last):
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/distributed/comm/tcp.py", line 297, in write
    raise StreamClosedError()
tornado.iostream.StreamClosedError: Stream is closed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/distributed/batched.py", line 115, in _background_send
    nbytes = yield coro
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/tornado/gen.py", line 767, in run
    value = future.result()
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/distributed/comm/tcp.py", line 307, in write
    convert_stream_closed_error(self, e)
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/distributed/comm/tcp.py", line 142, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed) Worker->Scheduler local=tcp://10.34.59.5:49164 remote=tcp://10.34.59.1:41731>: Stream is closed
2024-08-09 06:20:37,820 - distributed.nanny - INFO - Closing Nanny gracefully at 'tcp://10.34.59.5:35957'. Reason: scheduler-close
2024-08-09 06:20:37,821 - distributed.core - INFO - Received 'close-stream' from tcp://10.34.59.1:41731; closing.
2024-08-09 06:20:37,821 - distributed.nanny - INFO - Worker closed
2024-08-09 06:20:37,823 - distributed.core - INFO - Received 'close-stream' from tcp://10.34.59.1:41731; closing.
2024-08-09 06:20:37,823 - distributed.nanny - INFO - Worker closed
