2024-08-09 06:21:54,692 - distributed.nanny - INFO -         Start Nanny at: 'tcp://10.34.59.6:38613'
2024-08-09 06:21:54,696 - distributed.nanny - INFO -         Start Nanny at: 'tcp://10.34.59.6:41274'
2024-08-09 06:21:55,290 - distributed.diskutils - INFO - Found stale lock file and directory '/tmp/dask-scratch-space/worker-safrmdop', purging
2024-08-09 06:21:55,759 - distributed.worker - INFO -       Start worker at:     tcp://10.34.59.6:38424
2024-08-09 06:21:55,759 - distributed.worker - INFO -          Listening to:     tcp://10.34.59.6:38424
2024-08-09 06:21:55,759 - distributed.worker - INFO -           Worker name:           SLURMCluster-2-1
2024-08-09 06:21:55,759 - distributed.worker - INFO -          dashboard at:           10.34.59.6:39737
2024-08-09 06:21:55,759 - distributed.worker - INFO - Waiting to connect to:     tcp://10.34.59.1:34808
2024-08-09 06:21:55,759 - distributed.worker - INFO - -------------------------------------------------
2024-08-09 06:21:55,759 - distributed.worker - INFO -               Threads:                          1
2024-08-09 06:21:55,759 - distributed.worker - INFO -                Memory:                   1.86 GiB
2024-08-09 06:21:55,759 - distributed.worker - INFO -       Local Directory: /tmp/dask-scratch-space/worker-nogj_i04
2024-08-09 06:21:55,759 - distributed.worker - INFO - -------------------------------------------------
2024-08-09 06:21:55,763 - distributed.worker - INFO -       Start worker at:     tcp://10.34.59.6:39864
2024-08-09 06:21:55,763 - distributed.worker - INFO -          Listening to:     tcp://10.34.59.6:39864
2024-08-09 06:21:55,763 - distributed.worker - INFO -           Worker name:           SLURMCluster-2-0
2024-08-09 06:21:55,763 - distributed.worker - INFO -          dashboard at:           10.34.59.6:37436
2024-08-09 06:21:55,763 - distributed.worker - INFO - Waiting to connect to:     tcp://10.34.59.1:34808
2024-08-09 06:21:55,763 - distributed.worker - INFO - -------------------------------------------------
2024-08-09 06:21:55,763 - distributed.worker - INFO -               Threads:                          1
2024-08-09 06:21:55,763 - distributed.worker - INFO -                Memory:                   1.86 GiB
2024-08-09 06:21:55,763 - distributed.worker - INFO -       Local Directory: /tmp/dask-scratch-space/worker-8ko6w_c8
2024-08-09 06:21:55,764 - distributed.worker - INFO - -------------------------------------------------
2024-08-09 06:21:56,106 - distributed.worker - INFO - Starting Worker plugin shuffle
2024-08-09 06:21:56,107 - distributed.worker - INFO -         Registered to:     tcp://10.34.59.1:34808
2024-08-09 06:21:56,107 - distributed.worker - INFO - -------------------------------------------------
2024-08-09 06:21:56,107 - distributed.worker - INFO - Starting Worker plugin shuffle
2024-08-09 06:21:56,107 - distributed.core - INFO - Starting established connection to tcp://10.34.59.1:34808
2024-08-09 06:21:56,108 - distributed.worker - INFO -         Registered to:     tcp://10.34.59.1:34808
2024-08-09 06:21:56,108 - distributed.worker - INFO - -------------------------------------------------
2024-08-09 06:21:56,108 - distributed.core - INFO - Starting established connection to tcp://10.34.59.1:34808
2024-08-09 06:22:14,513 - distributed.worker - INFO - Stopping worker at tcp://10.34.59.6:39864. Reason: scheduler-close
2024-08-09 06:22:14,514 - distributed.worker - INFO - Stopping worker at tcp://10.34.59.6:38424. Reason: scheduler-close
2024-08-09 06:22:14,515 - distributed.batched - INFO - Batched Comm Closed <TCP (closed) Worker->Scheduler local=tcp://10.34.59.6:50824 remote=tcp://10.34.59.1:34808>
Traceback (most recent call last):
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/distributed/comm/tcp.py", line 297, in write
    raise StreamClosedError()
tornado.iostream.StreamClosedError: Stream is closed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/distributed/batched.py", line 115, in _background_send
    nbytes = yield coro
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/tornado/gen.py", line 767, in run
    value = future.result()
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/distributed/comm/tcp.py", line 307, in write
    convert_stream_closed_error(self, e)
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/distributed/comm/tcp.py", line 142, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed) Worker->Scheduler local=tcp://10.34.59.6:50824 remote=tcp://10.34.59.1:34808>: Stream is closed
2024-08-09 06:22:14,515 - distributed.batched - INFO - Batched Comm Closed <TCP (closed) Worker->Scheduler local=tcp://10.34.59.6:50822 remote=tcp://10.34.59.1:34808>
Traceback (most recent call last):
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/distributed/comm/tcp.py", line 297, in write
    raise StreamClosedError()
tornado.iostream.StreamClosedError: Stream is closed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/distributed/batched.py", line 115, in _background_send
    nbytes = yield coro
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/tornado/gen.py", line 767, in run
    value = future.result()
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/distributed/comm/tcp.py", line 307, in write
    convert_stream_closed_error(self, e)
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/distributed/comm/tcp.py", line 142, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed) Worker->Scheduler local=tcp://10.34.59.6:50822 remote=tcp://10.34.59.1:34808>: Stream is closed
2024-08-09 06:22:14,518 - distributed.nanny - INFO - Closing Nanny gracefully at 'tcp://10.34.59.6:38613'. Reason: scheduler-close
2024-08-09 06:22:14,518 - distributed.nanny - INFO - Closing Nanny gracefully at 'tcp://10.34.59.6:41274'. Reason: scheduler-close
slurmstepd: error: *** JOB 2330473 ON cl-node006 CANCELLED AT 2024-08-09T06:22:14 ***
2024-08-09 06:22:14,520 - distributed.core - INFO - Received 'close-stream' from tcp://10.34.59.1:34808; closing.
2024-08-09 06:22:14,521 - distributed.nanny - INFO - Worker closed
2024-08-09 06:22:14,521 - distributed.core - INFO - Received 'close-stream' from tcp://10.34.59.1:34808; closing.
2024-08-09 06:22:14,521 - distributed.nanny - INFO - Worker closed
