2024-08-09 06:29:22,186 - distributed.nanny - INFO -         Start Nanny at: 'tcp://10.34.59.8:45255'
2024-08-09 06:29:22,779 - distributed.diskutils - INFO - Found stale lock file and directory '/tmp/dask-scratch-space/worker-cs2hh6gs', purging
2024-08-09 06:29:23,302 - distributed.worker - INFO -       Start worker at:     tcp://10.34.59.8:41887
2024-08-09 06:29:23,302 - distributed.worker - INFO -          Listening to:     tcp://10.34.59.8:41887
2024-08-09 06:29:23,302 - distributed.worker - INFO -           Worker name:             SLURMCluster-7
2024-08-09 06:29:23,302 - distributed.worker - INFO -          dashboard at:           10.34.59.8:38582
2024-08-09 06:29:23,302 - distributed.worker - INFO - Waiting to connect to:     tcp://10.34.59.1:42937
2024-08-09 06:29:23,302 - distributed.worker - INFO - -------------------------------------------------
2024-08-09 06:29:23,303 - distributed.worker - INFO -               Threads:                          1
2024-08-09 06:29:23,303 - distributed.worker - INFO -                Memory:                   1.86 GiB
2024-08-09 06:29:23,303 - distributed.worker - INFO -       Local Directory: /tmp/dask-scratch-space/worker-d7a5wqpi
2024-08-09 06:29:23,303 - distributed.worker - INFO - -------------------------------------------------
2024-08-09 06:29:23,710 - distributed.worker - INFO - Starting Worker plugin shuffle
2024-08-09 06:29:23,711 - distributed.worker - INFO -         Registered to:     tcp://10.34.59.1:42937
2024-08-09 06:29:23,711 - distributed.worker - INFO - -------------------------------------------------
2024-08-09 06:29:23,711 - distributed.core - INFO - Starting established connection to tcp://10.34.59.1:42937
slurmstepd: error: *** JOB 2330555 ON cl-node008 CANCELLED AT 2024-08-09T06:29:42 ***
2024-08-09 06:29:42,816 - distributed.worker - INFO - Stopping worker at tcp://10.34.59.8:41887. Reason: scheduler-close
2024-08-09 06:29:42,818 - distributed.batched - INFO - Batched Comm Closed <TCP (closed) Worker->Scheduler local=tcp://10.34.59.8:47068 remote=tcp://10.34.59.1:42937>
Traceback (most recent call last):
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/distributed/comm/tcp.py", line 297, in write
    raise StreamClosedError()
tornado.iostream.StreamClosedError: Stream is closed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/distributed/batched.py", line 115, in _background_send
    nbytes = yield coro
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/tornado/gen.py", line 767, in run
    value = future.result()
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/distributed/comm/tcp.py", line 307, in write
    convert_stream_closed_error(self, e)
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/distributed/comm/tcp.py", line 142, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed) Worker->Scheduler local=tcp://10.34.59.8:47068 remote=tcp://10.34.59.1:42937>: Stream is closed
2024-08-09 06:29:42,820 - distributed.nanny - INFO - Closing Nanny gracefully at 'tcp://10.34.59.8:45255'. Reason: scheduler-close
2024-08-09 06:29:42,823 - distributed.core - INFO - Received 'close-stream' from tcp://10.34.59.1:42937; closing.
2024-08-09 06:29:42,824 - distributed.nanny - INFO - Worker closed
